### ISSUE TITLE
Just following your instructions from README leads me to this.

### ISSUE THREAD

**Issue by TheLostLegend** [spookygames/gdx-nativefilechooser#3]
Caused by: android.os.FileUriExposedException: file:/ exposed beyond app through Intent.getData()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:2141)
        at android.net.Uri.checkFileUriExposed(Uri.java:2391)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:11152)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:11125)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:11104)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1722)
        at android.app.Activity.startActivityForResult(Activity.java:5320)
        at android.app.Activity.startActivityForResult(Activity.java:5278)
        at games.spooky.gdx.nativefilechooser.android.AndroidFileChooser.chooseFile(AndroidFileChooser.java:180)

**Comment by arthurtemple** [comment]
Thanks for the feedback!

It looks like an issue with android when targeting sdk >= 24+.

I guess you could take inspiration from the answers to this StackOverflow question: https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed

**Comment by arthurtemple** [comment]
Should be better in next version, coming up asap. Please re-open if still needed.
